### PR TITLE
Fix reconnecting web socket timeout reuse

### LINKED ISSUE #31: Reconnecting web socket tests are flakey
It looks like there's some test pollution related to `setTimeout` in the reconnecting web socket, at least in Node. This may be due to some sort of underlying reuse of the timeout IDs. More importantly, it may be indicative of a real issue!

### PR DESCRIPTION
**Pull request by iredelmeier**
This fixes the flakey tests and related issues.

To observe the flakiness, checkout the commit prior to this one and run the tests with seeds 21227 (which will fail) and 21228 (which will pass), e.g., `npm test -- --seed=21227`

Closes #31

### CODE REVIEW

File: flux-sdk-common/src/utils/reconnecting-web-socket.js [hunk 1]
```diff
@@ -32,19 +32,21 @@ function ReconnectingWebSocket(fetchWebSocketPath, options = {}) {
...
     clearTimeout(attemptReconnectId);
+    clearTimeout(errorTimeoutId);
   }
 
   function reconnect() {
     if (!killed && !isReconnecting) {
       webSocket = null;
       isReconnecting = true;
-      attemptReconnectId = setTimeout(attemptReconnect, reconnectDelay);
+      attemptReconnectId = attemptReconnectId || setTimeout(attemptReconnect, reconnectDelay);
```
Comment (daishiflux) [inline flux-sdk-common/src/utils/reconnecting-web-socket.js]: Do we need this change even after your addition of clearing the attemptReconnectId timeout in onOpen below?
What remaining circumstances do we expect attemptReconnectId to be truthy even when !isReconnecting?

File: flux-sdk-common/spec/unit/utils/reconnect-web-socket-spec.js [hunk 2]
```diff
@@ -53,12 +55,11 @@ describe('utils.ReconnectingWebSocket', function() {
         .then(this.webSocketSpy.open)
         .then(callback);
     };
-
-    jasmine.clock().install();
   });
 
-  afterEach(function() {
+  afterEach(function(done) {
     jasmine.clock().uninstall();
```
Comment (daishiflux) [inline flux-sdk-common/spec/unit/utils/reconnect-web-socket-spec.js]: Please add comment explaining use of setTimeout
