### PR TITLE
Only add handlers to FluxWebSockets once

### LINKED ISSUE #1: Calling dataTable.openWebSocket multiple times causes user-added handlers to get called multiple times
To reproduce:

1. Create a data table object `dataTable`
1. Create a handler `logHandler` that logs the received message
1. Add the handler to the data table (`dataTable.addWebSocketHandler(logHandler)`)
1. Call `dataTable.openWebSocket()` twice
1. Observe that `logHandler` was called twice with the same message

### PR DESCRIPTION
**Pull request by iredelmeier**
This fixes a bug where reopening a given web socket
(e.g., via dataTable.openWebSocket) would cause all
user-defined handlers for that web socket to get
called once.

Fixes #1

### CODE REVIEW

File: flux-sdk-common/src/utils/flux-web-socket.js [hunk 1]
```diff
@@ -60,14 +60,22 @@ function FluxWebSocket(fetchWebSocketPath, options) {
     }));
   }
 
+  function hasHandler(subchannel, handler) {
```
Comment (daishiflux) [inline flux-sdk-common/src/utils/flux-web-socket.js]: Seems like handlers basically have set semantics. Maybe eventually make that more explicit by breaking out instead of manually implementing here?
