### PR TITLE
Fixes creation of valueless cells

### LINKED ISSUE #7: Updating a cell may cause unexpected behaviour
Since the cell update endpoint behaves more like a PUT request than a POST request, Cell.update behaves unexpectedly.

For example, keys may be overridden:
```js
// before: cell's description is a non-empty string
cell.update({ label: 'new label' })
// after: cell's description === ''
```

Alternatively, if the label isn't supplied, the cell might not change at all:
```js
// before: cell's description is 'old description'
cell.update({ description: 'new description' })
// after: cell's description is 'old description'
```

### PR DESCRIPTION
**Pull request by iredelmeier**
We cannot set the "IgnoreValue" flag to true when creating a cell, even if the user is not providing a value.

Closes #7

### CODE REVIEW

File: flux-sdk-common/spec/unit/models/cell-spec.js [hunk 1]
```diff
@@ -285,7 +285,7 @@ describe('models.Cell.static', function() {
             fluxOptions: {
               Metadata: true,
               ClientMetadata: { Label: 'NEW KEY' },
-              IgnoreValue: true,
+              IgnoreValue: false,
```
Comment (daishiflux) [inline flux-sdk-common/spec/unit/models/cell-spec.js]: Include a test for when IgnoreValue ends up true?
Also perhaps in an integration test please verify that values are ignored if this is set (even if a value is provided in the body).
